INSERT INTO DRIVER_INFO(ID,FIRST_NAME,LAST_NAME,CRED_SCORE,NR_ACC_VLTNS,LAST_ACC_VLTNS_DATE)
VALUES (-1,'Jon','Snow', 401 , 0, '2000-12-12');
INSERT INTO DRIVER_INFO(ID,FIRST_NAME,LAST_NAME,CRED_SCORE,NR_ACC_VLTNS,LAST_ACC_VLTNS_DATE)
VALUES (-2,'Arya','Stark', 401 , 1, '2000-12-12');
INSERT INTO DRIVER_INFO(ID,FIRST_NAME,LAST_NAME,CRED_SCORE,NR_ACC_VLTNS,LAST_ACC_VLTNS_DATE)
VALUES (-3,'Sansa','Stark', 401 , 1, '2000-12-12');
INSERT INTO DRIVER_INFO(ID,FIRST_NAME,LAST_NAME,CRED_SCORE,NR_ACC_VLTNS,LAST_ACC_VLTNS_DATE)
VALUES (-4,'Bran','Stark', 401 , 1, '2000-12-12');
INSERT INTO DRIVER_INFO(ID,FIRST_NAME,LAST_NAME,CRED_SCORE,NR_ACC_VLTNS,LAST_ACC_VLTNS_DATE)
VALUES (-5,'Cersei','Lannister', 100 , 3, '2019-5-12');
INSERT INTO DRIVER_INFO(ID,FIRST_NAME,LAST_NAME,CRED_SCORE,NR_ACC_VLTNS,LAST_ACC_VLTNS_DATE)
VALUES (-6,'Jaimie','Lannister', 300 , 2, '2000-12-12');
INSERT INTO DRIVER_INFO(ID,FIRST_NAME,LAST_NAME,CRED_SCORE,NR_ACC_VLTNS,LAST_ACC_VLTNS_DATE)
VALUES (-7,'Tyrion','Lannister', 400 , 0, '2000-12-12');
